# Praca Magisterska

# Wczytanie danych i bibliotek

In [509]:
import pandas as pd

pd.options.mode.chained_assignment = None
import numpy as np
import os

%load_ext nb_black

The nb_black extension is already loaded. To reload it, use:
  %reload_ext nb_black

In [510]:
path = "D:\Informatyka i ekonometria\praca magisterska\dane\Combined_Flights_2022.csv"
os.chdir(path)

In [511]:
df = pd.read_csv("Combined_Flights_2022.csv")
df.dropna(inplace=True)
df.reset_index(drop = True, inplace=True)
df

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,...,1140.0,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,...,744.0,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,...,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False,False,1435,1430.0,0.0,-5.0,...,1446.0,1543.0,4.0,1605,-18.0,0.0,-2.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,...,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3944911,2022-03-31,Republic Airlines,EYW,EWR,False,False,1617,1953.0,216.0,216.0,...,2012.0,2244.0,12.0,1929,207.0,1.0,12.0,1900-1959,5,0
3944912,2022-03-31,Republic Airlines,CLE,EWR,False,False,1418,1801.0,223.0,223.0,...,1815.0,1920.0,10.0,1609,201.0,1.0,12.0,1600-1659,2,0
3944913,2022-03-31,Republic Airlines,IAD,PIT,False,False,1750,2105.0,195.0,195.0,...,2119.0,2156.0,5.0,1901,180.0,1.0,12.0,1900-1959,1,0
3944914,2022-03-19,Republic Airlines,EWR,MEM,False,False,2035,2309.0,154.0,154.0,...,2323.0,47.0,5.0,2237,135.0,1.0,9.0,2200-2259,4,0
3944915,2022-03-08,Republic Airlines,ALB,ORD,False,False,1700,2318.0,378.0,378.0,...,2337.0,52.0,7.0,1838,381.0,1.0,12.0,1800-1859,3,0

In [512]:
df.head()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,...,1140.0,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,...,744.0,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,...,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False,False,1435,1430.0,0.0,-5.0,...,1446.0,1543.0,4.0,1605,-18.0,0.0,-2.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,...,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0

In [515]:
df.describe()

,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,...,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,DistanceGroup,DivAirportLandings,target
count,3.944916e+06,3.944916e+06,3.944916e+06,3.944916e+06,3.944916e+06,3.944916e+06,3.944916e+06,3.944916e+06,3.944916e+06,3.944916e+06,...,3.944916e+06,3.944916e+06,3.944916e+06,3.944916e+06,3.944916e+06,3.944916e+06,3.944916e+06,3.944916e+06,3.944916e+06,3.944916e+06
mean,1.328088e+03,1.334120e+03,1.594013e+01,1.301277e+01,1.457636e+03,1.578307e+01,1.110075e+02,1.413464e+02,1.358624e+02,7.988929e+02,...,1.356426e+03,1.454810e+03,7.888369e+00,1.484449e+03,7.528486e+00,2.164715e-01,-6.256103e-02,3.667419e+00,4.562835e-06,2.505339e-01
std,4.899073e+02,5.057184e+02,5.216240e+01,5.316724e+01,5.429405e+02,5.198424e+01,6.996246e+01,7.199693e+01,7.185501e+01,5.931635e+02,...,5.076589e+02,5.376202e+02,6.647231e+00,5.178388e+02,5.524625e+01,4.118393e-01,2.487442e+00,2.326462e+00,6.408237e-03,4.333205e-01
min,1.000000e+00,1.000000e+00,0.000000e+00,-7.800000e+01,1.000000e+00,0.000000e+00,8.000000e+00,-4.800000e+01,1.400000e+01,3.100000e+01,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-1.000000e+02,0.000000e+00,-2.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00
25%,9.130000e+02,9.160000e+02,0.000000e+00,-5.000000e+00,1.046000e+03,0.000000e+00,6.000000e+01,8.900000e+01,8.300000e+01,3.680000e+02,...,9.320000e+02,1.043000e+03,4.000000e+00,1.102000e+03,-1.400000e+01,0.000000e+00,-1.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00
50%,1.320000e+03,1.325000e+03,0.000000e+00,-2.000000e+00,1.459000e+03,0.000000e+00,9.400000e+01,1.240000e+02,1.190000e+02,6.430000e+02,...,1.338000e+03,1.456000e+03,6.000000e+00,1.510000e+03,-5.000000e+00,0.000000e+00,-1.000000e+00,3.000000e+00,0.000000e+00,0.000000e+00
75%,1.732000e+03,1.744000e+03,1.100000e+01,1.100000e+01,1.913000e+03,1.000000e+01,1.410000e+02,1.720000e+02,1.670000e+02,1.035000e+03,...,1.758000e+03,1.909000e+03,9.000000e+00,1.919000e+03,1.000000e+01,0.000000e+00,0.000000e+00,5.000000e+00,0.000000e+00,1.000000e+00
max,2.359000e+03,2.400000e+03,7.223000e+03,7.223000e+03,2.400000e+03,7.232000e+03,7.270000e+02,6.900000e+02,7.640000e+02,5.095000e+03,...,2.400000e+03,2.400000e+03,2.900000e+02,2.359000e+03,7.232000e+03,1.000000e+00,1.200000e+01,1.100000e+01,9.000000e+00,1.000000e+00

In [516]:
df['target'] = np.where(df.DepDelayMinutes > 10, 1,  0)
df.target.sum()/df.shape[0]

0.2505338516713664

In [517]:
df.Diverted = np.where(df.Diverted == "True", 1, 0)

In [518]:
df.Cancelled = np.where(df.Cancelled == "True", 1, 0)

In [519]:
df.FlightDate = pd.to_datetime(df.FlightDate)

In [520]:
df = df[
    [
        "FlightDate",
        "Year",
        "Month",
        "DayofMonth",
        "DayOfWeek",
        "Origin",
        "OriginState",
        "Dest",
        "DestCityName",
        "DestState",
        "DepTime",
        "DepDelay",
        "DepDel15",
        "TaxiOut",
        "TaxiIn",
        "CRSArrTime",
        "ArrTime",
        "ArrTimeBlk",
        "Cancelled",
        "Diverted",
        "CRSElapsedTime",
        "Distance",
        "DistanceGroup",
    ]
]

In [521]:
column = df.DepTime
date = df.FlightDate

column = [int(x) for x in column]
for i in range(0, len(column) - 1):
    if column[i] < 10:
        column[i] = "00:0" + str(column[i])
    elif column[i] < 60:
        column[i] = "00:" + str(column[i])
    else:
        column[i] = str(column[i])[:-2] + ":" + str(column[i])[-2:]
xd = [str(i) for i in column]
date = [str(i)[:-8] for i in date]
res = [i + j for i, j in zip(date, xd)]
res

['2022-04-04 11:23',
 '2022-04-04 7:28',
 '2022-04-04 15:14',
 '2022-04-04 14:30',
 '2022-04-04 11:35',
 '2022-04-04 9:52',
 '2022-04-04 21:36',
 '2022-04-04 11:17',
 '2022-04-04 14:14',
 '2022-04-04 9:47',
 '2022-04-04 15:46',
 '2022-04-04 7:04',
 '2022-04-04 13:58',
 '2022-04-04 10:08',
 '2022-04-04 12:55',
 '2022-04-04 9:37',
 '2022-04-04 13:22',
 '2022-04-04 11:12',
 '2022-04-04 18:00',
 '2022-04-04 19:54',
 '2022-04-04 18:10',
 '2022-04-04 9:55',
 '2022-04-04 20:27',
 '2022-04-04 18:29',
 '2022-04-04 12:19',
 '2022-04-04 8:54',
 '2022-04-04 20:21',
 '2022-04-04 12:20',
 '2022-04-04 17:32',
 '2022-04-04 16:06',
 '2022-04-04 16:31',
 '2022-04-04 6:55',
 '2022-04-04 18:49',
 '2022-04-04 10:45',
 '2022-04-04 9:45',
 '2022-04-04 18:25',
 '2022-04-04 6:51',
 '2022-04-04 19:04',
 '2022-04-04 21:37',
 '2022-04-04 16:34',
 '2022-04-04 12:09',
 '2022-04-04 17:11',
 '2022-04-04 13:38',
 '2022-04-04 19:28',
 '2022-04-04 14:54',
 '2022-04-04 16:24',
 '2022-04-04 11:48',
 '2022-04-04 15:53',
 '2022-04-04 5:59',
 '2022-04-04 6:12',
 '2022-04-04 10:14',
 '2022-04-04 13:25',
 '2022-04-04 17:35',
 '2022-04-04 7:27',
 '2022-04-04 14:33',
 '2022-04-04 11:25',
 '2022-04-04 9:54',
 '2022-04-04 10:30',
 '2022-04-04 13:02',
 '2022-04-04 18:30',
 '2022-04-04 14:45',
 '2022-04-04 8:55',
 '2022-04-04 8:26',
 '2022-04-04 19:15',
 '2022-04-04 16:00',
 '2022-04-04 8:43',
 '2022-04-04 11:54',
 '2022-04-04 16:37',
 '2022-04-04 8:25',
 '2022-04-04 22:02',
 '2022-04-04 5:55',
 '2022-04-04 13:45',
 '2022-04-04 6:19',
 '2022-04-04 14:07',
 '2022-04-04 12:23',
 '2022-04-04 19:54',
 '2022-04-04 20:57',
 '2022-04-04 5:54',
 '2022-04-04 10:56',
 '2022-04-04 15:43',
 '2022-04-04 10:26',
 '2022-04-04 18:02',
 '2022-04-04 17:14',
 '2022-04-04 15:29',
 '2022-04-04 12:29',
 '2022-04-04 13:23',
 '2022-04-04 13:58',
 '2022-04-04 17:19',
 '2022-04-04 10:38',
 '2022-04-04 17:28',
 '2022-04-04 13:30',
 '2022-04-04 17:30',
 '2022-04-04 17:58',
 '2022-04-04 14:10',
 '2022-04-04 14:43',
 '2022-04-04 7:05',
 '2022-04-04 17:37',
 '2022-04-04 17:04',
 '2022-04-04 17:28',
 '2022-04-04 8:06',
 '2022-04-04 13:58',
 '2022-04-04 15:02',
 '2022-04-04 8:48',
 '2022-04-04 7:37',
 '2022-04-04 16:00',
 '2022-04-04 13:50',
 '2022-04-04 19:40',
 '2022-04-04 8:46',
 '2022-04-04 11:14',
 '2022-04-04 12:52',
 '2022-04-04 8:36',
 '2022-04-04 18:47',
 '2022-04-04 11:05',
 '2022-04-04 15:57',
 '2022-04-04 15:36',
 '2022-04-04 17:19',
 '2022-04-04 6:45',
 '2022-04-04 11:53',
 '2022-04-04 9:24',
 '2022-04-04 6:49',
 '2022-04-04 18:03',
 '2022-04-04 11:13',
 '2022-04-04 5:57',
 '2022-04-04 19:51',
 '2022-04-04 10:17',
 '2022-04-04 21:03',
 '2022-04-04 16:48',
 '2022-04-04 13:57',
 '2022-04-04 18:10',
 '2022-04-04 11:26',
 '2022-04-04 9:28',
 '2022-04-04 16:38',
 '2022-04-04 6:27',
 '2022-04-04 5:52',
 '2022-04-04 11:09',
 '2022-04-04 17:49',
 '2022-04-04 10:38',
 '2022-04-04 13:51',
 '2022-04-04 7:47',
 '2022-04-04 19:23',
 '2022-04-04 10:51',
 '2022-04-04 14:34',
 '2022-04-04 15:10',
 '2022-04-04 9:07',
 '2022-04-04 9:21',
 '2022-04-04 12:32',
 '2022-04-04 19:29',
 '2022-04-04 20:24',
 '2022-04-04 7:26',
 '2022-04-04 6:40',
 '2022-04-04 10:58',
 '2022-04-04 18:47',
 '2022-04-04 18:02',
 '2022-04-04 5:58',
 '2022-04-04 6:15',
 '2022-04-04 12:50',
 '2022-04-04 17:55',
 '2022-04-04 8:38',
 '2022-04-04 13:13',
 '2022-04-04 13:47',
 '2022-04-04 14:49',
 '2022-04-04 7:28',
 '2022-04-04 15:52',
 '2022-04-04 17:24',
 '2022-04-04 13:05',
 '2022-04-04 17:24',
 '2022-04-04 13:46',
 '2022-04-04 17:42',
 '2022-04-04 14:08',
 '2022-04-04 14:01',
 '2022-04-04 8:02',
 '2022-04-04 11:51',
 '2022-04-04 9:09',
 '2022-04-04 8:41',
 '2022-04-04 17:27',
 '2022-04-04 7:34',
 '2022-04-04 10:54',
 '2022-04-04 9:05',
 '2022-04-04 15:39',
 '2022-04-04 8:43',
 '2022-04-04 18:20',
 '2022-04-04 16:40',
 '2022-04-04 5:37',
 '2022-04-04 15:53',
 '2022-04-04 18:46',
 '2022-04-04 14:44',
 '2022-04-04 14:14',
 '2022-04-04 18:15',
 '2022-04-04 5:18',
 '2022-04-04 15:37',
 '2022-04-04 10:28',
 '2022-04-04 14:39',
 '2022-04-04 11:03',
 '2022-04-04 11:22',
 '2022-04-04 13:44',
 '2022-04-04 6:51',
 '2022-04-04 11:05',
 '2022-04-04 12:53',
 '2022-04-04 16:32',
 '2022-04-04 21:10',
 '2022-04-04 9:27',
 '2022-04-04 18:24',
 '2022-04-04 14:01',
 '2022-04-04 15:44',
 '2022-04-04 10:32',
 '2022-04-04 7:23',
 '2022-04-04 6:24',
 '2022-04-04 17:55',
 '2022-04-04 19:44',
 '2022-04-04 12:20',
 '2022-04-04 12:52',
 '2022-04-04 13:55',
 '2022-04-04 8:44',
 '2022-04-04 9:55',
 '2022-04-04 19:59',
 '2022-04-04 11:52',
 '2022-04-04 13:55',
 '2022-04-04 14:33',
 '2022-04-04 12:19',
 '2022-04-04 18:15',
 '2022-04-04 18:18',
 '2022-04-04 16:34',
 '2022-04-04 8:30',
 '2022-04-04 7:02',
 '2022-04-04 13:23',
 '2022-04-04 13:55',
 '2022-04-04 12:02',
 '2022-04-04 17:32',
 '2022-04-04 11:18',
 '2022-04-04 16:53',
 '2022-04-04 11:10',
 '2022-04-04 7:03',
 '2022-04-04 7:06',
 '2022-04-04 17:54',
 '2022-04-04 10:35',
 '2022-04-04 10:27',
 '2022-04-04 8:47',
 '2022-04-04 14:36',
 '2022-04-04 14:04',
 '2022-04-04 11:20',
 '2022-04-04 8:20',
 '2022-04-04 13:56',
 '2022-04-04 8:40',
 '2022-04-04 6:35',
 '2022-04-04 8:49',
 '2022-04-04 19:48',
 '2022-04-04 9:20',
 '2022-04-04 7:49',
 '2022-04-04 17:53',
 '2022-04-04 12:31',
 '2022-04-04 11:32',
 '2022-04-04 13:22',
 '2022-04-04 8:22',
 '2022-04-04 14:29',
 '2022-04-04 19:37',
 '2022-04-04 17:00',
 '2022-04-04 8:56',
 '2022-04-04 13:38',
 '2022-04-04 17:51',
 '2022-04-04 8:25',
 '2022-04-04 19:50',
 '2022-04-04 7:58',
 '2022-04-04 20:24',
 '2022-04-04 10:33',
 '2022-04-04 17:27',
 '2022-04-04 7:01',
 '2022-04-04 8:28',
 '2022-04-04 19:28',
 '2022-04-04 21:01',
 '2022-04-04 13:57',
 '2022-04-04 8:44',
 '2022-04-04 18:09',
 '2022-04-04 15:12',
 '2022-04-04 14:08',
 '2022-04-04 6:26',
 '2022-04-04 10:20',
 '2022-04-04 16:36',
 '2022-04-04 18:47',
 '2022-04-04 5:54',
 '2022-04-04 10:30',
 '2022-04-04 12:15',
 '2022-04-03 20:06',
 '2022-04-03 9:13',
 '2022-04-03 18:42',
 '2022-04-03 9:11',
 '2022-04-03 16:29',
 '2022-04-03 11:35',
 '2022-04-03 9:50',
 '2022-04-03 11:57',
 '2022-04-03 14:04',
 '2022-04-03 12:35',
 '2022-04-03 11:00',
 '2022-04-03 9:20',
 '2022-04-03 14:39',
 '2022-04-03 22:00',
 '2022-04-03 11:10',
 '2022-04-03 14:17',
 '2022-04-03 17:26',
 '2022-04-03 18:12',
 '2022-04-03 6:50',
 '2022-04-03 13:04',
 '2022-04-03 18:27',
 '2022-04-03 8:01',
 '2022-04-03 15:10',
 '2022-04-03 17:28',
 '2022-04-03 21:34',
 '2022-04-03 14:42',
 '2022-04-03 17:41',
 '2022-04-03 17:25',
 '2022-04-03 13:44',
 '2022-04-03 8:55',
 '2022-04-03 17:00',
 '2022-04-03 6:42',
 '2022-04-03 9:08',
 '2022-04-03 10:19',
 '2022-04-03 15:53',
 '2022-04-03 12:57',
 '2022-04-03 15:51',
 '2022-04-03 15:48',
 '2022-04-03 7:16',
 '2022-04-03 9:21',
 '2022-04-03 17:55',
 '2022-04-03 12:25',
 '2022-04-03 19:47',
 '2022-04-03 21:35',
 '2022-04-03 12:34',
 '2022-04-03 14:51',
 '2022-04-03 16:04',
 '2022-04-03 12:11',
 '2022-04-03 20:15',
 '2022-04-03 14:37',
 '2022-04-03 14:51',
 '2022-04-03 18:08',
 '2022-04-03 10:54',
 '2022-04-03 9:20',
 '2022-04-03 14:19',
 '2022-04-03 9:23',
 '2022-04-03 15:26',
 '2022-04-03 12:59',
 '2022-04-03 17:45',
 '2022-04-03 18:21',
 '2022-04-03 17:28',
 '2022-04-03 13:14',
 '2022-04-03 11:08',
 '2022-04-03 5:42',
 '2022-04-03 19:40',
 '2022-04-03 9:55',
 '2022-04-03 19:47',
 '2022-04-03 14:15',
 '2022-04-03 11:21',
 '2022-04-03 8:06',
 '2022-04-03 13:13',
 '2022-04-03 5:56',
 '2022-04-03 10:45',
 '2022-04-03 16:48',
 '2022-04-03 19:00',
 '2022-04-03 14:06',
 '2022-04-03 15:12',
 '2022-04-03 5:53',
 '2022-04-03 10:06',
 '2022-04-03 17:41',
 '2022-04-03 18:09',
 '2022-04-03 15:40',
 '2022-04-03 20:01',
 '2022-04-03 13:58',
 '2022-04-03 10:38',
 '2022-04-03 19:02',
 '2022-04-03 15:39',
 '2022-04-03 18:29',
 '2022-04-03 14:21',
 '2022-04-03 17:11',
 '2022-04-03 9:14',
 '2022-04-03 13:00',
 '2022-04-03 13:53',
 '2022-04-03 11:09',
 '2022-04-03 10:57',
 '2022-04-03 22:14',
 '2022-04-03 17:54',
 '2022-04-03 11:09',
 '2022-04-03 7:50',
 '2022-04-03 10:43',
 '2022-04-03 14:28',
 '2022-04-03 15:02',
 '2022-04-03 19:05',
 '2022-04-03 10:00',
 '2022-04-03 13:23',
 '2022-04-03 20:07',
 '2022-04-03 10:54',
 '2022-04-03 18:28',
 '2022-04-03 8:34',
 '2022-04-03 13:03',
 '2022-04-03 10:52',
 '2022-04-03 20:00',
 '2022-04-03 23:00',
 '2022-04-03 17:06',
 '2022-04-03 10:52',
 '2022-04-03 17:49',
 '2022-04-03 16:15',
 '2022-04-03 13:22',
 '2022-04-03 19:06',
 '2022-04-03 15:30',
 '2022-04-03 17:44',
 '2022-04-03 9:35',
 '2022-04-03 7:20',
 '2022-04-03 5:56',
 '2022-04-03 16:26',
 '2022-04-03 15:50',
 '2022-04-03 17:21',
 '2022-04-03 13:45',
 '2022-04-03 15:11',
 '2022-04-03 21:24',
 '2022-04-03 19:38',
 '2022-04-03 19:35',
 '2022-04-03 16:40',
 '2022-04-03 20:15',
 '2022-04-03 10:59',
 '2022-04-03 19:03',
 '2022-04-03 14:34',
 '2022-04-03 14:56',
 '2022-04-03 11:58',
 '2022-04-03 22:33',
 '2022-04-03 12:34',
 '2022-04-03 7:02',
 '2022-04-03 16:55',
 '2022-04-03 22:10',
 '2022-04-03 18:16',
 '2022-04-03 14:09',
 '2022-04-03 14:39',
 '2022-04-03 7:57',
 '2022-04-03 14:31',
 '2022-04-03 11:28',
 '2022-04-03 8:51',
 '2022-04-03 21:48',
 '2022-04-03 11:50',
 '2022-04-03 17:28',
 '2022-04-03 15:34',
 '2022-04-03 6:57',
 '2022-04-03 11:28',
 '2022-04-03 17:12',
 '2022-04-03 22:17',
 '2022-04-03 6:00',
 '2022-04-03 16:31',
 '2022-04-03 7:05',
 '2022-04-03 10:03',
 '2022-04-03 17:31',
 '2022-04-03 20:49',
 '2022-04-03 14:22',
 '2022-04-03 17:03',
 '2022-04-03 6:54',
 '2022-04-03 8:25',
 '2022-04-03 12:27',
 '2022-04-03 12:29',
 '2022-04-03 10:43',
 '2022-04-03 16:04',
 '2022-04-03 13:52',
 '2022-04-03 16:14',
 '2022-04-03 13:44',
 '2022-04-03 18:37',
 '2022-04-03 10:27',
 '2022-04-03 10:27',
 '2022-04-03 17:45',
 '2022-04-03 13:06',
 '2022-04-03 19:34',
 '2022-04-03 18:08',
 '2022-04-03 7:44',
 '2022-04-03 19:51',
 '2022-04-03 12:13',
 '2022-04-03 13:08',
 '2022-04-03 11:54',
 '2022-04-03 17:54',
 '2022-04-03 17:06',
 '2022-04-03 13:27',
 '2022-04-03 14:15',
 '2022-04-03 6:22',
 '2022-04-03 13:51',
 '2022-04-03 19:49',
 '2022-04-03 14:09',
 '2022-04-03 7:20',
 '2022-04-03 9:50',
 '2022-04-03 18:40',
 '2022-04-03 15:12',
 '2022-04-03 13:15',
 '2022-04-03 9:10',
 '2022-04-03 14:46',
 '2022-04-03 5:56',
 '2022-04-03 11:24',
 '2022-04-03 16:42',
 '2022-04-03 11:29',
 '2022-04-03 9:16',
 '2022-04-03 13:08',
 '2022-04-03 20:21',
 '2022-04-03 19:47',
 '2022-04-03 9:15',
 '2022-04-03 14:40',
 '2022-04-03 11:18',
 '2022-04-03 11:59',
 '2022-04-03 19:33',
 '2022-04-03 14:47',
 '2022-04-03 15:21',
 '2022-04-03 14:52',
 '2022-04-03 19:51',
 '2022-04-03 11:15',
 '2022-04-03 9:14',
 '2022-04-03 12:05',
 '2022-04-03 12:06',
 '2022-04-03 17:06',
 '2022-04-03 8:27',
 '2022-04-03 13:01',
 '2022-04-03 15:38',
 '2022-04-03 14:20',
 '2022-04-03 21:54',
 '2022-04-03 16:20',
 '2022-04-03 14:30',
 '2022-04-03 11:05',
 '2022-04-03 13:28',
 '2022-04-03 19:19',
 '2022-04-03 17:23',
 '2022-04-03 9:24',
 '2022-04-03 17:19',
 '2022-04-03 10:07',
 '2022-04-03 12:28',
 '2022-04-03 9:56',
 '2022-04-03 17:31',
 '2022-04-03 12:55',
 '2022-04-03 11:45',
 '2022-04-03 8:59',
 '2022-04-03 18:51',
 '2022-04-03 15:16',
 '2022-04-03 11:31',
 '2022-04-03 16:40',
 '2022-04-03 9:25',
 '2022-04-03 15:24',
 '2022-04-03 15:42',
 '2022-04-03 11:34',
 '2022-04-03 9:48',
 '2022-04-03 21:32',
 '2022-04-03 11:44',
 '2022-04-03 15:16',
 '2022-04-03 9:48',
 '2022-04-03 9:23',
 '2022-04-03 13:53',
 '2022-04-03 16:32',
 '2022-04-03 11:26',
 '2022-04-03 13:20',
 '2022-04-03 15:20',
 '2022-04-03 12:29',
 '2022-04-03 9:32',
 '2022-04-03 13:28',
 '2022-04-03 11:13',
 '2022-04-03 8:55',
 '2022-04-03 17:49',
 '2022-04-03 19:38',
 '2022-04-03 18:07',
 '2022-04-03 9:39',
 '2022-04-03 13:48',
 '2022-04-03 20:22',
 '2022-04-03 13:29',
 '2022-04-03 18:27',
 '2022-04-03 12:22',
 '2022-04-03 8:49',
 '2022-04-03 20:24',
 '2022-04-03 12:27',
 '2022-04-03 17:23',
 '2022-04-03 15:41',
 '2022-04-03 16:56',
 '2022-04-03 9:24',
 '2022-04-03 13:28',
 '2022-04-03 10:44',
 '2022-04-03 9:44',
 '2022-04-03 9:34',
 '2022-04-03 18:23',
 '2022-04-03 6:53',
 '2022-04-03 17:35',
 '2022-04-03 21:37',
 '2022-04-03 16:35',
 '2022-04-03 11:21',
 '2022-04-03 13:03',
 '2022-04-03 17:13',
 '2022-04-03 13:27',
 '2022-04-03 19:38',
 '2022-04-03 15:01',
 '2022-04-03 16:32',
 '2022-04-03 11:56',
 '2022-04-03 12:32',
 '2022-04-03 16:47',
 '2022-04-03 6:00',
 '2022-04-03 10:15',
 '2022-04-03 13:19',
 '2022-04-03 8:34',
 '2022-04-03 14:24',
 '2022-04-03 11:39',
 '2022-04-03 9:49',
 '2022-04-03 13:07',
 '2022-04-03 19:27',
 '2022-04-03 8:51',
 '2022-04-03 8:23',
 '2022-04-03 20:48',
 '2022-04-03 16:45',
 '2022-04-03 8:37',
 '2022-04-03 11:51',
 '2022-04-03 17:13',
 '2022-04-03 21:58',
 '2022-04-03 5:57',
 '2022-04-03 13:16',
 '2022-04-03 6:42',
 '2022-04-03 14:27',
 '2022-04-03 12:40',
 '2022-04-03 19:56',
 '2022-04-03 21:08',
 '2022-04-03 16:03',
 '2022-04-03 16:14',
 '2022-04-03 10:19',
 '2022-04-03 21:31',
 '2022-04-03 19:26',
 '2022-04-03 15:32',
 '2022-04-03 12:33',
 '2022-04-03 13:22',
 '2022-04-03 14:04',
 '2022-04-03 17:29',
 '2022-04-03 10:39',
 '2022-04-03 17:22',
 '2022-04-03 13:30',
 '2022-04-03 17:40',
 '2022-04-03 18:04',
 '2022-04-03 14:08',
 '2022-04-03 15:07',
 '2022-04-03 7:02',
 '2022-04-03 17:34',
 '2022-04-03 16:58',
 '2022-04-03 17:39',
 '2022-04-03 8:18',
 '2022-04-03 13:50',
 '2022-04-03 14:44',
 '2022-04-03 8:53',
 '2022-04-03 7:41',
 '2022-04-03 16:01',
 '2022-04-03 13:48',
 '2022-04-03 10:45',
 '2022-04-03 12:31',
 '2022-04-03 6:39',
 '2022-04-03 18:44',
 '2022-04-03 16:55',
 '2022-04-03 15:33',
 '2022-04-03 17:05',
 '2022-04-03 6:47',
 '2022-04-03 11:53',
 '2022-04-03 9:26',
 '2022-04-03 6:49',
 '2022-04-03 18:10',
 '2022-04-03 11:03',
 '2022-04-03 19:52',
 '2022-04-03 10:25',
 '2022-04-03 21:55',
 '2022-04-03 16:52',
 '2022-04-03 13:50',
 '2022-04-03 18:15',
 '2022-04-03 10:46',
 '2022-04-03 9:32',
 '2022-04-03 16:36',
 '2022-04-03 6:23',
 '2022-04-03 11:06',
 '2022-04-03 17:47',
 '2022-04-03 14:16',
 '2022-04-03 10:35',
 '2022-04-03 13:54',
 '2022-04-03 6:08',
 '2022-04-03 19:35',
 '2022-04-03 17:29',
 '2022-04-03 10:51',
 '2022-04-03 14:41',
 '2022-04-03 8:26',
 '2022-04-03 9:21',
 '2022-04-03 12:35',
 '2022-04-03 14:02',
 '2022-04-03 19:46',
 '2022-04-03 20:26',
 '2022-04-03 7:10',
 '2022-04-03 6:43',
 '2022-04-03 11:11',
 '2022-04-03 11:42',
 '2022-04-03 18:48',
 '2022-04-03 19:57',
 '2022-04-03 6:03',
 '2022-04-03 6:15',
 '2022-04-03 17:57',
 '2022-04-03 8:38',
 '2022-04-03 13:05',
 '2022-04-03 9:29',
 '2022-04-03 14:44',
 '2022-04-03 7:47',
 '2022-04-03 13:55',
 '2022-04-03 15:54',
 '2022-04-03 13:06',
 '2022-04-03 17:21',
 '2022-04-03 13:47',
 '2022-04-03 13:58',
 '2022-04-03 8:06',
 '2022-04-03 8:58',
 '2022-04-03 12:51',
 '2022-04-03 16:50',
 '2022-04-03 8:53',
 '2022-04-03 17:22',
 '2022-04-03 8:55',
 '2022-04-03 10:56',
 '2022-04-03 9:05',
 '2022-04-03 15:41',
 '2022-04-03 8:40',
 '2022-04-03 18:14',
 '2022-04-03 16:50',
 '2022-04-03 5:36',
 '2022-04-03 15:46',
 '2022-04-03 19:13',
 '2022-04-03 14:45',
 '2022-04-03 15:48',
 '2022-04-03 18:20',
 '2022-04-03 5:21',
 '2022-04-03 15:39',
 '2022-04-03 14:45',
 '2022-04-03 10:55',
 '2022-04-03 11:25',
 '2022-04-03 13:46',
 '2022-04-03 6:12',
 '2022-04-03 11:13',
 '2022-04-03 12:55',
 '2022-04-03 16:33',
 '2022-04-03 17:29',
 '2022-04-03 21:26',
 '2022-04-03 9:25',
 '2022-04-03 17:45',
 '2022-04-03 13:57',
 '2022-04-03 15:47',
 '2022-04-03 10:19',
 '2022-04-03 7:24',
 '2022-04-03 17:51',
 '2022-04-03 19:47',
 '2022-04-03 13:03',
 '2022-04-03 12:44',
 '2022-04-03 15:01',
 '2022-04-03 8:46',
 '2022-04-03 9:52',
 '2022-04-03 19:58',
 '2022-04-03 11:47',
 '2022-04-03 13:52',
 '2022-04-03 14:26',
 '2022-04-03 11:32',
 '2022-04-03 18:08',
 '2022-04-03 18:19',
 '2022-04-03 16:36',
 '2022-04-03 8:28',
 '2022-04-03 6:50',
 '2022-04-03 13:20',
 '2022-04-03 13:56',
 '2022-04-03 18:24',
 '2022-04-03 11:46',
 '2022-04-03 22:24',
 '2022-04-03 16:56',
 '2022-04-03 11:14',
 '2022-04-03 7:05',
 '2022-04-03 7:20',
 '2022-04-03 17:55',
 '2022-04-03 10:36',
 '2022-04-03 10:19',
 '2022-04-03 8:58',
 '2022-04-03 14:39',
 '2022-04-03 11:45',
 '2022-04-03 6:23',
 '2022-04-03 13:57',
 '2022-04-03 11:03',
 '2022-04-03 6:22',
 '2022-04-03 8:47',
 '2022-04-03 19:49',
 '2022-04-03 9:08',
 '2022-04-03 7:58',
 '2022-04-03 18:38',
 '2022-04-03 12:41',
 '2022-04-03 11:35',
 '2022-04-03 13:12',
 '2022-04-03 8:21',
 '2022-04-03 14:33',
 '2022-04-03 19:55',
 '2022-04-03 16:59',
 '2022-04-03 8:49',
 '2022-04-03 13:46',
 '2022-04-03 17:51',
 '2022-04-03 8:26',
 '2022-04-03 19:52',
 '2022-04-03 7:58',
 '2022-04-03 20:34',
 '2022-04-03 10:27',
 '2022-04-03 18:02',
 '2022-04-03 6:57',
 '2022-04-03 8:38',
 '2022-04-03 17:54',
 '2022-04-03 21:06',
 '2022-04-03 13:52',
 '2022-04-03 8:44',
 '2022-04-03 18:01',
 '2022-04-03 15:17',
 '2022-04-03 14:46',
 '2022-04-03 7:47',
 '2022-04-03 10:26',
 '2022-04-03 16:50',
 '2022-04-03 18:39',
 '2022-04-03 6:18',
 '2022-04-03 10:33',
 '2022-04-03 12:15',
 '2022-04-02 20:15',
 '2022-04-02 9:15',
 '2022-04-02 19:12',
 '2022-04-02 7:09',
 '2022-04-02 17:02',
 '2022-04-02 9:46',
 '2022-04-02 9:58',
 '2022-04-02 10:14',
 '2022-04-02 12:19',
 '2022-04-02 12:06',
 '2022-04-02 9:58',
 '2022-04-02 9:17',
 '2022-04-02 16:03',
 '2022-04-02 22:06',
 '2022-04-02 10:19',
 '2022-04-02 17:15',
 '2022-04-02 18:05',
 '2022-04-02 6:58',
 '2022-04-02 12:23',
 '2022-04-02 18:22',
 '2022-04-02 7:04',
 '2022-04-02 14:20',
 '2022-04-02 17:26',
 '2022-04-02 21:34',
 '2022-04-02 14:19',
 '2022-04-02 7:04',
 '2022-04-02 16:24',
 '2022-04-02 16:54',
 '2022-04-02 11:41',
 '2022-04-02 8:55',
 '2022-04-02 17:14',
 '2022-04-02 6:41',
 '2022-04-02 6:52',
 '2022-04-02 9:52',
 '2022-04-02 11:53',
 '2022-04-02 6:54',
 '2022-04-02 17:54',
 '2022-04-02 7:02',
 '2022-04-02 9:17',
 '2022-04-02 17:44',
 '2022-04-02 14:16',
 '2022-04-02 19:52',
 '2022-04-02 21:44',
 '2022-04-02 12:28',
 '2022-04-02 14:48',
 '2022-04-02 16:15',
 '2022-04-02 21:45',
 '2022-04-02 14:33',
 '2022-04-02 14:45',
 '2022-04-02 8:36',
 '2022-04-02 13:33',
 '2022-04-02 9:21',
 '2022-04-02 7:02',
 '2022-04-02 14:31',
 '2022-04-02 12:58',
 '2022-04-02 8:59',
 '2022-04-02 18:04',
 '2022-04-02 17:23',
 '2022-04-02 13:14',
 '2022-04-02 11:13',
 '2022-04-02 6:01',
 '2022-04-02 19:39',
 '2022-04-02 16:27',
 '2022-04-02 9:54',
 '2022-04-02 9:41',
 '2022-04-02 19:48',
 '2022-04-02 15:05',
 '2022-04-02 8:10',
 '2022-04-02 5:54',
 '2022-04-02 15:37',
 '2022-04-02 13:19',
 '2022-04-02 15:14',
 '2022-04-02 6:56',
 '2022-04-02 9:50',
 '2022-04-02 15:34',
 '2022-04-02 11:55',
 '2022-04-02 13:58',
 '2022-04-02 9:09',
 '2022-04-02 11:40',
 '2022-04-02 11:13',
 '2022-04-02 17:51',
 '2022-04-02 10:58',
 '2022-04-02 8:50',
 '2022-04-02 13:20',
 '2022-04-02 17:22',
 '2022-04-02 11:09',
 '2022-04-02 9:17',
 '2022-04-02 16:09',
 '2022-04-02 17:47',
 '2022-04-02 13:23',
 '2022-04-02 19:00',
 '2022-04-02 15:33',
 '2022-04-02 10:04',
 '2022-04-02 6:21',
 '2022-04-02 15:07',
 '2022-04-02 17:40',
 '2022-04-02 15:16',
 '2022-04-02 18:08',
 '2022-04-02 14:49',
 '2022-04-02 14:35',
 '2022-04-02 11:48',
 '2022-04-02 5:54',
 '2022-04-02 16:58',
 '2022-04-02 11:53',
 '2022-04-02 12:09',
 '2022-04-02 10:37',
 '2022-04-02 19:22',
 '2022-04-02 11:50',
 '2022-04-02 15:40',
 '2022-04-02 8:49',
 '2022-04-02 20:27',
 '2022-04-02 7:00',
 '2022-04-02 17:39',
 '2022-04-02 17:03',
 '2022-04-02 8:44',
 '2022-04-02 12:33',
 '2022-04-02 10:46',
 '2022-04-02 13:53',
 '2022-04-02 20:38',
 '2022-04-02 10:36',
 '2022-04-02 10:34',
 '2022-04-02 8:52',
 '2022-04-02 22:35',
 '2022-04-02 11:49',
 '2022-04-02 19:35',
 '2022-04-02 13:12',
 '2022-04-02 19:56',
 '2022-04-02 14:01',
 '2022-04-02 11:42',
 '2022-04-02 12:02',
 '2022-04-02 10:09',
 '2022-04-02 17:50',
 '2022-04-02 12:04',
 '2022-04-02 14:18',
 '2022-04-02 6:29',
 '2022-04-02 12:50',
 '2022-04-02 20:00',
 '2022-04-02 15:49',
 '2022-04-02 13:57',
 '2022-04-02 7:18',
 '2022-04-02 9:55',
 '2022-04-02 15:05',
 '2022-04-02 12:02',
 '2022-04-02 9:21',
 '2022-04-02 14:43',
 '2022-04-02 5:56',
 '2022-04-02 18:00',
 '2022-04-02 14:27',
 '2022-04-02 9:59',
 '2022-04-02 10:27',
 '2022-04-02 16:37',
 '2022-04-02 7:10',
 '2022-04-02 19:39',
 '2022-04-02 20:19',
 '2022-04-02 7:04',
 '2022-04-02 14:29',
 '2022-04-02 9:59',

In [522]:
column = df.DepTime
date = df.FlightDate


def date_hour(date, column):
    column = [int(x) for x in column]
    for i in range(0, len(column)):
        if column[i] < 10:
            column[i] = "00:0" + str(column[i])
        elif column[i] < 60:
            column[i] = "00:" + str(column[i])
        elif column[i] >= 2400:
            column[i] = "00:00"
        else:
            column[i] = str(column[i])[:-2] + ":" + str(column[i])[-2:]
    xd = [str(i) for i in column]
    date = [str(i)[:-8] for i in date]
    res = [i + j for i, j in zip(date, xd)]
    datetime = pd.to_datetime(res)
    return res


df["DepDateTime"] = date_hour(df.FlightDate, df.DepTime)

In [523]:
df

,FlightDate,Year,Month,DayofMonth,DayOfWeek,Origin,OriginState,Dest,DestCityName,DestState,...,TaxiIn,CRSArrTime,ArrTime,ArrTimeBlk,Cancelled,Diverted,CRSElapsedTime,Distance,DistanceGroup,DepDateTime
0,2022-04-04,2022,4,4,1,GJT,CO,DEN,"Denver, CO",CO,...,8.0,1245,1228.0,1200-1259,0,0,72.0,212.0,1,2022-04-04 11:23
1,2022-04-04,2022,4,4,1,HRL,TX,IAH,"Houston, TX",TX,...,9.0,849,848.0,0800-0859,0,0,77.0,295.0,2,2022-04-04 7:28
2,2022-04-04,2022,4,4,1,DRO,CO,DEN,"Denver, CO",CO,...,14.0,1639,1636.0,1600-1659,0,0,70.0,251.0,2,2022-04-04 15:14
3,2022-04-04,2022,4,4,1,IAH,TX,GPT,"Gulfport/Biloxi, MS",MS,...,4.0,1605,1547.0,1600-1659,0,0,90.0,376.0,2,2022-04-04 14:30
4,2022-04-04,2022,4,4,1,DRO,CO,DEN,"Denver, CO",CO,...,8.0,1245,1251.0,1200-1259,0,0,70.0,251.0,2,2022-04-04 11:35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3944911,2022-03-31,2022,3,31,4,EYW,FL,EWR,"Newark, NJ",NJ,...,12.0,1929,2256.0,1900-1959,0,0,192.0,1196.0,5,2022-03-31 19:53
3944912,2022-03-31,2022,3,31,4,CLE,OH,EWR,"Newark, NJ",NJ,...,10.0,1609,1930.0,1600-1659,0,0,111.0,404.0,2,2022-03-31 18:01
3944913,2022-03-31,2022,3,31,4,IAD,VA,PIT,"Pittsburgh, PA",PA,...,5.0,1901,2201.0,1900-1959,0,0,71.0,182.0,1,2022-03-31 21:05
3944914,2022-03-19,2022,3,19,6,EWR,NJ,MEM,"Memphis, TN",TN,...,5.0,2237,52.0,2200-2259,0,0,182.0,946.0,4,2022-03-19 23:09
3944915,2022-03-08,2022,3,8,2,ALB,NY,ORD,"Chicago, IL",IL,...,7.0,1838,59.0,1800-1859,0,0,158.0,723.0,3,2022-03-08 23:18